version: "3.9"

volumes:
  sockets:

x-api: &api
  build: .
  cpus: "0.45"
  mem_limit: "160m"
  volumes:
    - sockets:/sockets
  restart: unless-stopped

services:
  lb:
    image: haproxy:lts-alpine
    cpus: "0.1"
    mem_limit: "30m"

    ports:
      - "9999:9999"

    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
      - sockets:/sockets:ro

    depends_on:
      - api1
      - api2
    restart: unless-stopped

  api1:
    <<: *api
    hostname: api1
    environment:
      SOCKET_PATH: /sockets/api1.sock

  api2:
    <<: *api
    hostname: api2
    environment:
      SOCKET_PATH: /sockets/api2.sock
